spring.application.name=storage-service

server.port=${PORT:8080}
storage.base-path=${STORAGE_PATH:./storage-data}

management.endpoint.health.show-details=always

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB